### ISSUE TITLE
Is this complete?

### ISSUE THREAD

**Issue by thedrow** [kevinswiber/node-siren#1]
I'd like to port it to Python.

**Comment by kevinswiber** [comment]
@thedrow I haven't looked at this in a while, honestly.  I don't recall there being much here since Siren is just JSON.  I'll take a look and get back to you some time next week, likely.  Again, sorry for the delay.  I must have missed a whole bunch of GitHub action.

**Comment by jchannon** [comment]
Just tried to run this with node 5.3.0 and npm 3.3.12 and using `node siren.js` its blank or `node example.js` returns an error so I assume not complete? 😄

**Comment by kevinswiber** [comment]
@jchannon It's complete, but not documented.  The example API that was being used in `example.js` is no longer active.

I'm actively using this Siren client through [zrx](https://github.com/zettajs/zrx), which is an API-specific wrapper.
